### ISSUE TITLE
T-Pose for high FPS values

### ISSUE THREAD

**Issue by erri120** [SlavicPotato/SSEDisplayTweaks#1]
There is an _interesting_ bug where you T-Pose while strafing, using [Movement Behavior Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/38950?tab=bugs) and having more than 60 fps. Thought `MovementThreshold` would help but that was not the case.
Created an issue here so I hope you could take a look at why you'd T-Pose with more than 60fps when strafing.

**Comment by SlavicPotato** [comment]
If it were a widespread engine issue I might look into a fix, but in this case it might be better to take a look at those specific MBO animations and determine what exactly is causing this. You'll have to ask the author for a fix, I see there's already a thread in their bug reports.
