### ISSUE TITLE
Needs update for SKSE 2.2.2

### ISSUE THREAD

**Issue by Lazalatin** [SlavicPotato/SSEDisplayTweaks#3]
Hi there,

first the obligatory: Thank you for your work. My Ultra-Wide Screen is only of use for Skyrim AE because of your work on this mod ❤️ 

In case this has not been brought to your attention already: There has been updates to the Skyrim AE and in result to SKSE.
When fired up it lists this mod as built for a previous version set of Skyrim AE and SKSE and therefore would need an update.

If you need additional resources or information just let me know. In the meantime I hope this issue can be resolved easily.
I would love to build this myself and contribute in a more constructive way, but unfortunately I am bound to using Proton as I am all in for linux. (And I assume that it is not advised to try to build this repo with mono only)

Regards and thanks in advance
Lazalatin

**Comment by SlavicPotato** [comment]
That SKSE warning message would only pop up if you had 0.5.10 or earlier installed, grab the current version from nexus.

**Comment by Lazalatin** [comment]
Maybe I misread the new version in nexus, but anyhow this is fixed. Thank you!
